"""
Django settings for AstroBot project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "astro.testdomain.su"]

USE_I18N = True
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'UTC'
USE_L10N = True
USE_TZ = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    "https://astro.testdomain.su"
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = '/www/static/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',

    'tgbot',
    'rangefilter',
    'solo',
    'nested_admin',
    'jazzmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',    
]

ROOT_URLCONF = 'AstroBot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AstroBot.wsgi.application'

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC  = ("'self'",)
CSP_STYLE_SRC   = ("'self'",)

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Администрирование Astro Bot",
    "site_header": "Astro Bot Admin",
    "site_brand": "AstroBot",
    # и другие ваши опции…

    "navigation": [
        # Блок «APOD»
        {
            "app": "tgbot",
            "models": ["tgbot.apodapikey", "tgbot.apodfile"],
            "label": "🚀 APOD",
        },
        # Блок «Статьи»
        {
            "app": "tgbot",
            "models": [
                "tgbot.articlessection",
                "tgbot.articlessubsection",
                "tgbot.article"
            ],
            "label": "📰 Статьи",
        },
        # Блок «Конфигурация бота»
        {
            "app": "tgbot",
            "models": ["tgbot.telegrambottoken", "tgbot.configuration"],
            "label": "⚙️ Настройки бота",
        },
        # Блок «Глоссарий»
        {
            "app": "tgbot",
            "models": ["tgbot.glossary"],
            "label": "📖 Глоссарий",
        },
        # Блок «Интересные факты»
        {
            "app": "tgbot",
            "models": ["tgbot.interestingfact", "tgbot.dailysubscription"],
            "label": "💡 Интересные факты",
        },
        # Блок «SSH-ключи и Сервер»
        {
            "app": "tgbot",
            "models": ["tgbot.sshkey", "tgbot.server"],
            "label": "🔑 SSH и Сервер",
        },
        # Блок «Пользователи Telegram»
        {
            "app": "tgbot",
            "models": ["tgbot.telegramuser", "tgbot.sentmessage"],
            "label": "👤 Пользователи",
        },
        # Блок «Квизы»
        {
            "app": "tgbot",
            "models": [
                "tgbot.quiztopic", "tgbot.quizlevel", "tgbot.quiz",
                "tgbot.question", "tgbot.choice",
                "tgbot.userquizsession", "tgbot.userquizanswer",
            ],
            "label": "📚 Квизы",
        },
        # … можно дальше по остальным моделям
    ]
}