"""
Django settings for AstroBot project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from tgbot.logics.constants import Constants

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["localhost", Constants.APP_DOMAIN]

USE_I18N = True
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'UTC'
USE_L10N = True
USE_TZ = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    Constants.APP_URL
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = '/www/static/'


# Application definition

INSTALLED_APPS = [
    'admin_reorder',
    'nested_inline',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tgbot',
    'rangefilter',
    'solo',
]

MIDDLEWARE = [
    'admin_reorder.middleware.ModelAdminReorder',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',    
]

ROOT_URLCONF = 'AstroBot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AstroBot.wsgi.application'

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC  = ("'self'",)
CSP_STYLE_SRC   = ("'self'",)

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ADMIN_REORDER = (
    # 🚀 APOD
    {
        'app': 'tgbot',
        'label': '🚀 APOD',
        'models': (
            'tgbot.ApodApiKey',
            'tgbot.ApodFile',
        ),
    },
    # 📰 Статьи
    {
        'app': 'tgbot',
        'label': '📰 Статьи',
        'models': (
            'tgbot.ArticlesSection',
            'tgbot.ArticlesSubsection',
            'tgbot.Article',
        ),
    },
    # ⚙️ Настройки бота
    {
        'app': 'tgbot',
        'label': '⚙️ Настройки бота',
        'models': (
            'tgbot.TelegramBotToken',
            'tgbot.Configuration',
        ),
    },
    # 📖 Глоссарий
    {
        'app': 'tgbot',
        'label': '📖 Глоссарий',
        'models': (
            'tgbot.Glossary',
        ),
    },
    # 💡 Интересные факты
    {
        'app': 'tgbot',
        'label': '💡 Интересные факты',
        'models': (
            'tgbot.InterestingFact',
            'tgbot.DailySubscription',
        ),
    },
    # 🔑 SSH и Сервер
    {
        'app': 'tgbot',
        'label': '🔑 SSH и Сервер',
        'models': (
            'tgbot.SSHKey',
            'tgbot.Server',
        ),
    },
    # 👤 Пользователи
    {
        'app': 'tgbot',
        'label': '👤 Пользователи',
        'models': (
            'tgbot.TelegramUser',
            'tgbot.SentMessage',
        ),
    },
    # 📚 Квизы
    {
        'app': 'tgbot',
        'label': '📚 Квизы',
        'models': (
            'tgbot.QuizTopic',
            'tgbot.QuizLevel',
            'tgbot.Quiz',
            'tgbot.Question',
            'tgbot.Choice',
            'tgbot.UserQuizSession',
            'tgbot.UserQuizAnswer',
        ),
    },
)